# Site settings
title: Dachi's Blog 达迟的博客
email: dachi.xu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dachi's Personal Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dachicj.com" # the base hostname & protocol for your site
twitter_username: DachiXu
github_username:  DachiCoding

# Build settings
markdown: kramdown

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

