# Site settings
title: Dachi's Blog 达迟的博客
email: dachi.xu@gmail.com
description: Dachi's Personal Blog.
url: http://dachicj.com
github_username:  DachiCoding
exclude:

markdown: kramdown
theme: minima
